name: CI-Polaris-Basic
on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Polaris Scan
      id: polaris-scan
      uses: blackduck-inc/black-duck-security-scan@SIGINT-4250
      with:
        ### SCANNING: Required fields
        polaris_server_url: ${{ vars.POLARIS_URL }}
        polaris_access_token: ${{ secrets.POLARIS_TOKEN }}
        polaris_assessment_types: SAST
        
        ### SCANNING: Optional fields
        # polaris_application_name: ${{ github.event.repository.name }}
        # polaris_project_name: ${{ github.event.repository.name }}

                ### PULL REQUEST COMMENTS: Uncomment below to enable
        # polaris_prComment_enabled: true 
        # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

                ### SARIF report parameters
        polaris_reports_sarif_create: true
        #polaris_upload_sarif_report: true
        polaris_test_sast_location: hybrid
        include_diagnostics: true
                ### Signature scan
        #polaris_test_sca_type: "SCA-SIGNATURE"

                ### Mark build status if policy violating issues are found
        # mark_build_status: 'success'

                ### Uncomment below configuration to add custom logic based on return status
        # - name: cmdLine
        #   id: cmdLine
        #   run: |
        #     EXIT_CODE=${{ steps.polaris-scan.outputs.status }}
        #     echo "Polaris Scan exit status - $EXIT_CODE"
