name: Polaris Security Scan
on:
  push:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  pull_request:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  workflow_dispatch: {}
jobs:
  polaris:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Polaris Security Scan
        id: polaris-scan
        uses: blackduck-inc/black-duck-security-scan@SIGINT-3342
        with:
          polaris_server_url: 'https://pim.dev.polaris.blackduck.com/'
          polaris_access_token: 'mvia9pjdnt4ildk86vfm6nl4juci3gpc6lf4di5d9nnkia1753e6l8kbrkp7llcipe0d9aqdicqn0'
          polaris_assessment_types: SCA
          include_diagnostics: true
          coverity_version: '2023.6.0'
          bridgecli_download_url: 'https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/3.9.4rc1/bridge-cli-bundle-3.9.4rc1-macos_arm.zip'
