# Test Case: Run Polaris Sast by setting valid Coverity Version
# Priority: P1
# Expected: Valid supported tool downloaded, scan succeeds, SARIF created

name: TC01 - Polaris SAST with Valid Coverity Version

on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]
  workflow_dispatch: {}

jobs:
  polaris:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Polaris Security Scan
        id: polaris-scan
        uses: blackduck-inc/black-duck-security-scan@SIGINT-3342
        with:
          polaris_server_url: ${{ vars.PIM_POLARIS_URL }}
          polaris_access_token: ${{ secrets.PIM_POLARIS_TOKEN }}
          polaris_assessment_types: 'SCA,SAST'
          polaris_test_sast_type: 'SAST_FULL'
          polaris_reports_sarif_create: true
          coverity_version: '2024.6.0'  # Valid supported version
          bridgecli_download_url: 'https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/3.9.5rc1/bridge-cli-bundle-3.9.5rc1-macos_arm.zip'
